name: .NET
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ steps.release.outputs.version }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
    - name: Release
      id: release
      uses: rymndhng/release-on-push-action@v0.22.0
      with:
        bump_version_scheme: minor
        tag_prefix: v
  build:
    runs-on: ubuntu-latest
    needs: release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: needs.release.outputs.version
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r win-x64 -c release -p:Version=${{ needs.release.outputs.version }} -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true --framework net6.0
    - name: Add Release files
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        tag: ${{ needs.release.outputs.tag_name }}
        artifacts: GitCheckout/bin/Release/net5.0/win-x64/publish/GitCheckout.exe
